[worker] fix: Model engine parameter offload (#4777)
### What does this PR do?

Errors below are for running the script in the Test section.

Because `ActorRolloutRefWorker.wake_up` always moves the model to the
CPU, when going from train -> validation, model parameters are on the
CPU regardless of `_is_offload_param`:

```bash
  File "/nvme-data/jacob/verl/verl/workers/engine/fsdp/transformer_impl.py", line 657, in get_per_tensor_param
    params = self.module.state_dict()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2256, in state_dict
    hook(self, prefix, keep_vars)
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 777, in _pre_state_dict_hook
    _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 294, in _full_pre_state_dict_hook
    _common_unshard_pre_state_dict_hook(
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 161, in _common_unshard_pre_state_dict_hook
    _enter_unshard_params_ctx(
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 125, in _enter_unshard_params_ctx
    fsdp_state._unshard_params_ctx[module].__enter__()
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 199, in _unshard_fsdp_state_params
    _unshard(state, handle, computation_stream, computation_stream)
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 290, in _unshard
    ran_pre_unshard = handle.pre_unshard()
                      ^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_flat_param.py", line 1303, in pre_unshard
    self._check_on_compute_device(self.flat_param)
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/fsdp/_flat_param.py", line 2582, in _check_on_compute_device
    _p_assert(
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/distributed/utils.py", line 159, in _p_assert
    raise AssertionError(s)
AssertionError: Expects tensor to be on the compute device cuda:0, was on cpu

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Additionally, when `trainer.val_before_train=False`, optimizer
parameters are never moved off CPU:

```bash
  File "/nvme-data/jacob/verl/verl/workers/engine/fsdp/transformer_impl.py", line 554, in optimizer_step
    self.optimizer.step()
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/lr_scheduler.py", line 133, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/optimizer.py", line 516, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/optimizer.py", line 81, in _use_grad
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/adam.py", line 247, in step
    adam(
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/optimizer.py", line 149, in maybe_fallback
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/adam.py", line 949, in adam
    func(
  File "/data/jacob/anaconda3/envs/verl/lib/python3.12/site-packages/torch/optim/adam.py", line 447, in _single_tensor_adam
    exp_avg.lerp_(grad, 1 - device_beta1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Test

```bash
gsm8k_train_path=$DATA_DIR/gsm8k/train.parquet
gsm8k_test_path=$DATA_DIR/gsm8k/test.parquet

train_files="['$gsm8k_train_path']"
test_files="['$gsm8k_test_path']"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=1024 \
    data.max_prompt_length=1024 \
    data.max_response_length=512 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=40 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console"]' \
    trainer.project_name='verl_grpo_example_gsm8k_math' \
    trainer.experiment_name='qwen_05' \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.resume_mode=disable \
    trainer.use_legacy_worker_impl=disable \
    trainer.total_epochs=15 $@
```